# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default=0, verbose_name='用例id')),
                ('case_name', models.CharField(max_length=30, verbose_name='用例名称')),
                ('case_step', models.CharField(max_length=1000, verbose_name='用例步骤')),
            ],
        ),
    ]
