# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(default='0', max_length=10, verbose_name='用例id')),
                ('case_name', models.CharField(max_length=30, verbose_name='用例名称')),
                ('has_automatic', models.BooleanField(default=False, verbose_name='是否自动化')),
                ('test_report', models.CharField(max_length=200, verbose_name='测试报告')),
                ('class_name', models.CharField(default='', max_length=50, verbose_name='所属测试类')),
                ('test_method', models.CharField(default='', max_length=50, verbose_name='所属测试方法')),
                ('test_file', models.CharField(default='', max_length=50, verbose_name='所属测试文件')),
                ('test_result', models.NullBooleanField(default=None, verbose_name='上次测试结果')),
                ('steps', models.TextField(default='', verbose_name='用例步骤')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
    ]
