# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=30, verbose_name='用例名称')),
                ('test_report', models.CharField(max_length=200, verbose_name='测试报告')),
                ('test_result', models.NullBooleanField(default=None, verbose_name='上次测试结果')),
                ('steps', models.ManyToManyField(to='basicData.StepsForCases', verbose_name='用例步骤')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
    ]
