# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=30, verbose_name='元素名称')),
                ('access_method', models.CharField(choices=[('id', 'id'), ('xpath', 'xpath'), ('link', 'link')], max_length=10, verbose_name='获取方式')),
                ('access_path', models.CharField(default='None', max_length=100, verbose_name='获取值')),
                ('frame_name', models.CharField(default='default', max_length=30, verbose_name='所在frame')),
            ],
            options={
                'verbose_name': '元素',
                'verbose_name_plural': '元素',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_des', models.CharField(default='', max_length=100, verbose_name='步骤描述')),
                ('actions', models.CharField(choices=[('点击', '点击'), ('填写', '填写'), ('切换', '切换'), ('选择', '选择'), ('上传', '上传'), ('检查', '检查')], max_length=2, verbose_name='执行动作')),
                ('parameter', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='参数')),
                ('wait_time', models.IntegerField(default=1, verbose_name='执行完等待时间')),
                ('element_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicData.Element', verbose_name='元素名称')),
            ],
            options={
                'verbose_name': '步骤',
                'verbose_name_plural': '步骤',
            },
        ),
        migrations.CreateModel(
            name='StepsForCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('execution_order', models.IntegerField(verbose_name='执行顺序')),
                ('step_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicData.Steps', verbose_name='步骤描述')),
            ],
            options={
                'verbose_name': '用例步骤配置',
                'verbose_name_plural': '用例步骤配置',
            },
        ),
    ]
