# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDriven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('data', models.CharField(max_length=100, verbose_name='数据')),
            ],
            options={
                'verbose_name': '数据驱动',
                'verbose_name_plural': '数据驱动',
            },
        ),
    ]
