# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicData', '0002_datadriven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadriven',
            name='data',
            field=models.TextField(max_length=500, verbose_name='数据'),
        ),
    ]
